# Generated by Django 4.2.7 on 2025-08-26 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100, unique=True, verbose_name='ID de paiement')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Montant')),
                ('currency', models.CharField(default='XOF', max_length=3, verbose_name='Devise')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('cancelled', 'Annulé')], default='pending', max_length=20, verbose_name='Statut')),
                ('paydunya_token', models.CharField(blank=True, max_length=100, verbose_name='Token PayDunya')),
                ('paydunya_receipt_url', models.URLField(blank=True, verbose_name='URL de reçu PayDunya')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('customer_email', models.EmailField(max_length=254, verbose_name='Email du client')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='Téléphone du client')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Terminé le')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Paiement',
                'verbose_name_plural': 'Paiements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='Événement')),
                ('message', models.TextField(verbose_name='Message')),
                ('data', models.JSONField(default=dict, verbose_name='Données')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment', verbose_name='Paiement')),
            ],
            options={
                'verbose_name': 'Log de paiement',
                'verbose_name_plural': 'Logs de paiement',
                'ordering': ['-created_at'],
            },
        ),
    ]
