# Generated by Django 4.2.7 on 2025-08-26 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='paydunya_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Référence PayDunya'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('wave_direct', 'Wave Direct')], default='paydunya', max_length=20, verbose_name='Méthode de paiement'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wave_payment_code',
            field=models.CharField(blank=True, max_length=100, verbose_name='Code de paiement Wave'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wave_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Numéro Wave'),
        ),
    ]
