# Generated by Django 4.2.7 on 2025-08-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_paydunya_reference_payment_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='wave_qr_code',
            field=models.TextField(blank=True, verbose_name='QR Code Wave'),
        ),
        migrations.AddField(
            model_name='payment',
            name='wave_transaction_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='ID Transaction Wave'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('wave_direct', 'Wave Direct'), ('wave_qr', 'Wave QR Code')], default='paydunya', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
