# Generated by Django 4.2.7 on 2025-08-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_payment_wave_qr_code_payment_wave_transaction_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='wave_qr_code',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('paydunya', 'PayDunya'), ('wave_direct', 'Wave Direct')], default='paydunya', max_length=20, verbose_name='Méthode de paiement'),
        ),
    ]
