# Generated by Django 4.2.7 on 2025-08-31 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_jerseycustomization_cartitemcustomization'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=50, verbose_name='Texte personnalisé')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.jerseycustomization', verbose_name='Personnalisation')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='orders.orderitem', verbose_name='Article de commande')),
            ],
            options={
                'verbose_name': "Personnalisation d'article de commande",
                'verbose_name_plural': "Personnalisations d'articles de commande",
            },
        ),
    ]
