# Generated by Django 4.2.7 on 2025-08-31 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JerseyCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name="Nom de l'option")),
                ('customization_type', models.CharField(choices=[('name', 'Nom/Numéro'), ('badge', 'Badge/Emblème'), ('sponsor', 'Sponsor')], max_length=20, verbose_name='Type de personnalisation')),
                ('badge_type', models.CharField(blank=True, choices=[('liga', 'Liga'), ('uefa', 'UEFA'), ('champions', 'Champions League'), ('europa', 'Europa League'), ('premier', 'Premier League'), ('bundesliga', 'Bundesliga'), ('serie_a', 'Serie A'), ('ligue_1', 'Ligue 1')], max_length=20, verbose_name='Type de badge')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
            ],
            options={
                'verbose_name': 'Personnalisation de maillot',
                'verbose_name_plural': 'Personnalisations de maillots',
                'ordering': ['customization_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CartItemCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_text', models.CharField(blank=True, max_length=50, verbose_name='Texte personnalisé')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prix total')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('cart_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customizations', to='cart.cartitem', verbose_name='Article du panier')),
                ('customization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.jerseycustomization', verbose_name='Personnalisation')),
            ],
            options={
                'verbose_name': "Personnalisation d'article",
                'verbose_name_plural': "Personnalisations d'articles",
            },
        ),
    ]
