# Generated by Django 4.2.7 on 2025-08-31 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_jerseycustomization_cartitemcustomization'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jerseycustomization',
            unique_together={('customization_type', 'badge_type', 'name')},
        ),
    ]
